<?xml version="1.0" encoding="UTF-8"?><testrun name="tp0" project="tp0" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="tdd.tp0.AppTest" time="0.002">
    <testcase name="testApp" classname="tdd.tp0.AppTest" time="0.001">
      <failure>junit.framework.AssertionFailedError&#13;
	at junit.framework.Assert.fail(Assert.java:47)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:20)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:27)&#13;
	at tdd.tp0.AppTest.testApp(AppTest.java:36)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:154)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:127)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&#13;
	at junit.framework.TestResult.run(TestResult.java:109)&#13;
	at junit.framework.TestCase.run(TestCase.java:118)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:208)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:203)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:131)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
